import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'tl';
type TParams = Record<string, string | number>;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, params?: TParams) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations for the entire app
const translations = {
  en: {
    // Common
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.wallet': 'Wallet',
    'common.back': 'Back',
    
    // Vendor Home
    'vendor.greeting': (params: TParams) => `${params.time}, ${params.name}`,
    'vendor.goodMorning': 'Good morning',
    'vendor.goodAfternoon': 'Good afternoon',
    'vendor.goodEvening': 'Good evening',
    'vendor.todayEarnings': "Today's Earnings",
    'vendor.paymentsToday': (params: TParams) => `${params.count} payment${params.count !== 1 ? 's' : ''} today`,
    'vendor.allTimeEarnings': 'All-time',
    'vendor.totalPayments': 'Payments',
    'vendor.showQR': 'Show My QR',
    'vendor.showQRSub': 'Display code to accept payment',
    'vendor.utang': 'Utang',
    'vendor.utangSub': 'Installment credit',
    'vendor.recentPayments': 'Recent Payments',
    'vendor.viewAll': 'View all',
    'vendor.loadFailed': 'Failed to load',
    'vendor.retry': 'Retry',
    'vendor.emptyTitle': 'No payments yet',
    'vendor.emptyDesc': 'Share your QR to start receiving',
    'vendor.showQRBtn': 'Show my QR',
    'vendor.stallOpen': 'Stall is open',
    'vendor.stallClosed': 'Stall is closed',
    'vendor.tapToClose': 'Tap to close',
    'vendor.tapToOpen': 'Tap to open',
    'vendor.statusToastOpen': 'Stall set to OPEN. Customers can see you live.',
    'vendor.statusToastClosed': 'Stall set to CLOSED. You won\'t appear in the live directory.',
    'vendor.statusError': 'Could not update status',
    
    // Vendor Apply
    'apply.title': 'Apply as Vendor',
    'apply.subtitle': 'Submit stall info. Admin will approve your registration.',
    'apply.connectWallet': 'Connect Wallet',
    'apply.registryNotConfigured': 'Vendor registry not configured',
    'apply.registryHint': 'Set VITE_VENDOR_REGISTRY_CONTRACT_ID before new vendor applications can be submitted.',
    'apply.registryNotConfiguredShort': 'Registry not configured',
    'apply.selectStallError': 'Select a stall number first.',
    'apply.successToast': 'Application submitted! Waiting for admin approval.',
    'apply.successTitle': 'Application Submitted!',
    'apply.successDesc': 'Admin will review and approve your registration.',
    'apply.yourDetails': 'Your Details',
    'apply.stallName': 'Stall Name',
    'apply.stall': 'Stall',
    'apply.product': 'Product',
    'apply.phone': 'Phone',
    'apply.viewOnExpert': 'View on Stellar Expert',
    'apply.stallNameLabel': 'Stall Name',
    'apply.stallNamePlaceholder': 'e.g. Aling Nena Sari-Sari',
    'apply.productTypeLabel': 'Product Type',
    'apply.selectStallLabel': 'Select Stall',
    'apply.phoneLabel': 'Phone',
    'apply.optional': 'optional',
    'apply.paymentWallet': 'Payment wallet',
    'apply.submitting': 'Submitting...',
    'apply.submitButton': 'Submit Application',
    'apply.available': 'Available',
    'apply.occupied': 'Occupied',
    'apply.selected': 'Selected',
    'apply.section': 'Section',
    'apply.stallSelected': (params: TParams) => `Stall ${params.stall} selected`,
    
    // Vendor Transactions
    'transactions.header': 'All Earnings',
    'transactions.allTimeSub': 'XLM all-time',
    'transactions.todayEarnings': "Today's Earnings",
    'transactions.paymentsToday': 'Payments Today',
    'transactions.incomeProofPack': 'Income Proof Pack',
    'transactions.incomeProofDesc': 'Exportable vendor proof with source labels and Testnet caveats.',
    'transactions.transactions': 'Transactions',
    'transactions.totalXlm': 'Total XLM',
    'transactions.phpEst': 'PHP est.',
    'transactions.dateRange': 'Date range',
    'transactions.unavailable': 'Unavailable',
    'transactions.paymentData': 'Payment data',
    'transactions.repaymentData': 'Repayment data',
    'transactions.liveProof': 'Live proof',
    'transactions.customers': 'Customers',
    'transactions.present': 'Present',
    'transactions.missing': 'Missing',
    'transactions.attached': 'Attached',
    'transactions.notAttached': 'Not attached',
    'transactions.needed': 'Needed',
    'transactions.paymentRows': 'Payment rows',
    'transactions.liveHash': 'Live hash',
    'transactions.repayments': 'Repayments',
    'transactions.caveats': 'Caveats',
    'transactions.certificate': 'Certificate',
    'transactions.print': 'Print',
    'transactions.copyLiveHash': 'Copy live hash',
    'transactions.captureHashHint': 'Capture one real Testnet payment before sharing this certificate outside the demo team.',
    'transactions.recoveryDesk': 'Transaction Recovery Desk',
    'transactions.recoveryDesc': 'Receipt lookup, resend path, and sponsor diagnostics for customer payment issues.',
    'transactions.receiptLookup': 'Receipt lookup',
    'transactions.noReceiptYet': 'No receipt yet',
    'transactions.checkReceipt': 'Check receipt',
    'transactions.resendPath': 'Resend path',
    'transactions.sponsorDiagnostics': 'Sponsor diagnostics',
    'transactions.lookupByHash': 'Lookup by hash/reference',
    'transactions.lookupHelp': 'Paste the exact transaction hash, contract payment ID, or local receipt reference from a customer message.',
    'transactions.lookupPlaceholder': 'Hash, #42, or proof ref',
    'transactions.useLatest': 'Use latest',
    'transactions.clear': 'Clear',
    'transactions.openMatchedReceipt': 'Open matched receipt',
    'transactions.copyReference': 'Copy reference',
    'transactions.receiptReference': 'Receipt reference',
    'transactions.searchReceipts': 'Search receipts',
    'transactions.searchPlaceholder': 'Hash, memo, source, amount',
    'transactions.searchResultInfo': (params: TParams) => `Showing ${params.shown} of ${params.total} receipt rows. Exports use the selected period and current search filter.`,
    'transactions.failedTitle': 'Failed to load',
    'transactions.retry': 'Retry',
    'transactions.emptyTitle': 'No transactions yet',
    'transactions.emptyDesc': 'Share your QR code to receive your first payment',
    'transactions.showQr': 'Show QR',
    'transactions.noMatching': 'No matching receipts',
    'transactions.noMatchingHint': 'Try a hash, customer wallet, memo, source label, or amount.',
    'transactions.clearSearch': 'Clear search',

    // Scan
    'scan.title': 'Scan to Pay',
    'scan.manualTitle': 'Enter Address',
    'scan.payTitle': 'Pay Vendor',
    'scan.confirmTitle': 'Confirm Payment',
    'scan.doneTitle': 'Payment Sent!',
    'scan.utangOfferTitle': 'Installment Offer',
    'scan.utangDoneTitle': 'Accepted!',
    'scan.walletRequiredDetail': 'Connect your wallet before scanning payment QRs or accepting installment offers.',
    'scan.scanHeader': 'Scan QR',
    'scan.scanSub': 'Payment QR and utang offer — auto-detect',
    'scan.vendorAddressLabel': 'Vendor Wallet Address',
    'scan.vendorAddressHint': '56-character Stellar address starting with G',
    'scan.continue': 'Continue',
    'scan.payingTo': 'Paying to',
    'scan.amountToPay': 'Amount to Pay',
    'scan.priceLock': 'Price lock',
    'scan.expires': 'Expires',
    'scan.onChainReceipt': 'On-chain receipt — recorded by PalengkePayment',
    'scan.gasless': 'Gasless — fees sponsored, zero cost to you',
    'scan.confirmAndSign': 'Confirm and Sign',
    'scan.paymentComplete': 'Payment Complete!',
    'scan.toVendor': (params: TParams) => `to ${params.name}`,
    'scan.dualReceipt': 'Dual-currency receipt',
    'scan.customerPaid': 'Customer paid',
    'scan.settledOnStellar': 'Settled on Stellar',
    'scan.digitalReceipt': 'Digital Receipt',
    'scan.stellarExpert': 'Stellar Expert',
    'scan.payAgain': 'Pay Again',
    'scan.home': 'Home',
    'scan.installmentOffer': 'Installment Credit Offer',
    'scan.reviewBeforeAccept': 'Review before accepting',
    'scan.itemsBought': 'Items Bought',
    'scan.interval': 'interval',
    'scan.vendor': 'Vendor',
    'scan.contractNotConfigured': 'Contract not configured',
    'scan.contractHint': 'This offer can be reviewed, but it cannot be accepted until VITE_UTANG_ESCROW_CONTRACT_ID is set.',
    'scan.acceptAndSign': 'Accept and Sign',
    'scan.confirmInWallet': 'Confirm in your wallet…',
    'scan.confirmWalletHint': 'On mobile: open LOBSTR app and approve.',
    'scan.tryAgain': 'Try Again',
    'scan.agreementAccepted': 'Agreement Accepted!',
    'scan.agreementActive': 'Installment plan is now active.',
    'scan.viewUtang': 'View Utang',
    'scan.utangWrongWallet': 'This installment offer is assigned to another customer wallet',
    'scan.utangFailed': 'Transaction failed — check wallet and try again',
    'scan.interval.weekly': 'weekly',
    'scan.interval.biweekly': 'biweekly',
    'scan.interval.monthly': 'monthly',
    'scan.interval.every': (params: TParams) => `every ${params.days}d`,
    'scan.manualEntry': 'Manual entry',
    'scan.uploadQR': 'Upload QR image',
    'scan.bottomHint': 'Align QR code within the brackets',
    
    // Vendor Utang
    'vendorUtang.title': 'Utang (BNPL)',
    'vendorUtang.subtitle': 'Manage installment agreements',
    'vendorUtang.newUtang': 'New Utang',
    'vendorUtang.itemsRequired': 'Enter items description',
    'vendorUtang.validAmountRequired': 'Enter a valid amount',
    'vendorUtang.validWalletRequired': 'Enter a valid Stellar wallet address (G..., 56 chars)',
    'vendorUtang.transactionCancelled': 'Transaction cancelled',
    'vendorUtang.showQRToCustomer': 'Show QR to Customer',
    'vendorUtang.serviceFee': 'Service Fee',
    'vendorUtang.newAgreement': 'New Agreement',
    'vendorUtang.totalOutstanding': 'Total Outstanding',
    'vendorUtang.activeAgreements': (params: TParams) => `${params.count} active agreement${params.count !== 1 ? 's' : ''}`,
    'vendorUtang.collectionsReport': 'Collections Report',
    'vendorUtang.collectionsDesc': 'Summary of active, completed, overdue, and defaulted agreements.',
    'vendorUtang.active': 'Active',
    'vendorUtang.completed': 'Completed',
    'vendorUtang.overdue': 'Overdue',
    'vendorUtang.defaulted': 'Defaulted',
    'vendorUtang.outstanding': 'Outstanding',
    'vendorUtang.collected': 'Collected',
    'vendorUtang.loadFailed': 'Could not load agreements',
    'vendorUtang.retry': 'Retry',
    'vendorUtang.noAgreements': 'No agreements yet',
    'vendorUtang.noFilteredAgreements': (params: TParams) => `No ${params.filter} agreements`,
    'vendorUtang.emptyDesc': 'Create an installment agreement for a customer via QR or manual entry',
    'vendorUtang.escrowWarning': 'Set VITE_UTANG_ESCROW_CONTRACT_ID to enable BNPL.',
    'vendorUtang.customerWalletAddress': 'Customer Wallet Address',
    'vendorUtang.scanCustomerWallet': "Scan customer's wallet QR",
    'vendorUtang.items': 'Items',
    'vendorUtang.itemsHint': '(what they\'re buying on credit)',
    'vendorUtang.itemsPlaceholder': 'e.g. 5kg rice, 2kg pork, vegetables',
    'vendorUtang.totalAmount': 'Total Amount (XLM)',
    'vendorUtang.installments': 'Installments',
    'vendorUtang.interval': 'Interval',
    'vendorUtang.generateQRCode': 'Generate QR Code',
    'vendorUtang.createCustomerQR': 'Create Customer QR',
    'vendorUtang.agreementSummary': 'Agreement Summary',
    'vendorUtang.serviceFeeTitle': 'PalengkePay Service Fee',
    'vendorUtang.serviceFeeDesc': 'QR utang creation fee',
    'vendorUtang.serviceFeeNote': 'One-time fee per QR agreement. Paid to PalengkePay to register this installment on-chain.',
    'vendorUtang.payAndGenerateQR': (params: TParams) => `Pay ${params.fee} XLM & Generate QR`,
    'vendorUtang.confirmInWallet': 'Confirm in wallet…',
    'vendorUtang.downloadQR': 'Download QR Image',
    'vendorUtang.howItWorks': 'How it works',
    'vendorUtang.step1': 'Show this QR to your customer',
    'vendorUtang.step2': 'Customer opens PalengkePay → My Utang → tap Scan',
    'vendorUtang.step3': 'Customer reviews details and taps Accept',
    'vendorUtang.step4': 'Agreement registers on-chain automatically',
    'vendorUtang.done': 'Done',

    // Customer Utang
    'customerUtang.title': 'My Utang',
    'customerUtang.subtitle': 'Your installment plans',
    'customerUtang.uploadQR': 'Upload QR',
    'customerUtang.reading': 'Reading…',
    'customerUtang.uploadErrorInvalid': 'This QR is not an installment offer. Use Scan to Pay for payment QRs.',
    'customerUtang.uploadErrorRead': 'Could not read QR from image. Try a clearer photo.',
    'customerUtang.connectWalletDetail': 'Connect your wallet to review installment plans and accept vendor credit offers.',
    'customerUtang.contractNotConfigured': 'Installment contract not configured',
    'customerUtang.contractHint': 'Set VITE_UTANG_ESCROW_CONTRACT_ID before customers can load or accept installment plans.',
    'customerUtang.loadFailed': 'Could not load installment plans',
    'customerUtang.retry': 'Retry',
    'customerUtang.totalDue': 'Total Due — Next Installments',
    'customerUtang.activePlans': (params: TParams) => `${params.count} active plan${params.count !== 1 ? 's' : ''}`,
    'customerUtang.filter.active': 'Active',
    'customerUtang.filter.defaulted': 'Defaulted',
    'customerUtang.filter.completed': 'Completed',
    'customerUtang.filter.all': 'All',
    'customerUtang.emptyActive': 'No active plans',
    'customerUtang.emptyFiltered': (params: TParams) => `No ${params.filter} plans`,
    'customerUtang.emptyDesc': 'Ask your vendor for an installment QR, then scan or upload.',
    'customerUtang.scanQR': 'Scan QR',
    'customerUtang.installmentOffer': 'Installment Credit Offer',
    'customerUtang.reviewBeforeAccept': 'Review before accepting',
    'customerUtang.items': 'Items',
    'customerUtang.total': 'total',
    'customerUtang.interval': 'interval',
    'customerUtang.vendor': 'Vendor',
    'customerUtang.acceptAndSign': 'Accept and Sign',
    'customerUtang.confirmInWallet': 'Confirm in your wallet…',
    'customerUtang.confirmWalletHint': 'On mobile: open LOBSTR app and approve.',
    'customerUtang.agreementAccepted': 'Agreement accepted!',
    'customerUtang.viewOnExpert': 'View on Stellar Expert',
    'customerUtang.close': 'Close',
    'customerUtang.tryAgain': 'Try again',
    'customerUtang.offerWrongWallet': 'This installment offer is assigned to another customer wallet',
    'customerUtang.offerFailed': 'Transaction failed — check wallet and try again',
    'customerUtang.payInstallment': 'Pay Installment',
    'customerUtang.installmentNumber': (params: TParams) => `Installment ${params.current} of ${params.total}`,
    'customerUtang.confirmPayment': 'Confirm Payment',
    'customerUtang.preparing': 'Preparing…',
    'customerUtang.processing': 'Processing…',
    'customerUtang.paymentComplete': 'Payment complete!',
    'customerUtang.interval.weekly': 'weekly',
    'customerUtang.interval.biweekly': 'biweekly',
    'customerUtang.interval.monthly': 'monthly',
    'customerUtang.interval.every': (params: TParams) => `every ${params.days}d`,
    
    // Vendor QR
    'qr.connectWalletDetail': 'Connect your vendor wallet to display the QR code customers use for payment.',
    'qr.yourQRCode': 'Your QR Code',
    'qr.myQRCode': 'My QR Code',
    'qr.registerFirst': 'Register first',
    'qr.stall': 'Stall',
    'qr.registerStallFirst': 'Register your stall first',
    'qr.registryUnavailable': 'Vendor registry unavailable',
    'qr.registerHint': 'Your customer QR appears after your vendor profile is registered.',
    'qr.registryHint': 'Set the vendor registry contract ID before QR profiles can load.',
    'qr.applyAsVendor': 'Apply as Vendor',
    'qr.bottomHint': 'Customer scans to pay · works offline',
    'qr.printReady': 'Print-ready QR kit',
    'qr.posterPreview': 'Poster and sticker preview',
    'qr.printKit': 'Print QR kit',
    'qr.scanToPay': 'Scan to pay',
    'qr.step1': 'Open PalengkePay',
    'qr.step2': 'Scan this QR',
    'qr.step3': 'Confirm in wallet',
    'qr.sticker': 'Sticker',
    'qr.vendorQR': 'Vendor QR',
    'qr.stickerHint': 'Customer scans to pay by wallet.',
    
    // Vendor Profile
    'profile.connectWalletDetail': 'Connect your vendor wallet to view or update your stall profile.',
    'profile.addressCopied': 'Address copied to clipboard!',
    'profile.disconnected': 'Wallet disconnected',
    'profile.vendor': 'Vendor',
    'profile.copyAddress': 'Copy address',
    'profile.active': 'Active',
    'profile.inactive': 'Inactive',
    'profile.disconnect': 'Disconnect',
    'profile.disconnectTitle': 'Disconnect Wallet?',
    'profile.disconnectMessage': 'Are you sure you want to disconnect your wallet? You will need to reconnect to access your vendor profile.',
    'profile.cancel': 'Cancel',
    'profile.disconnectConfirm': 'Disconnect',
    'profile.disconnecting': 'Disconnecting...',
    'profile.withdrawEarnings': 'Withdraw earnings',
    'profile.withdrawDesc': 'Cash out XLM → PHP via PDAX',
    'profile.ratings': 'ratings',
    'profile.noRatingsShort': 'No ratings yet',
    'profile.transactions': 'Transactions',
    'profile.volume': 'Volume',
    'profile.stallDetails': 'Stall Details',
    'profile.edit': 'Edit',
    'profile.noProfile': 'No vendor profile yet',
    'profile.registryUnavailable': 'Vendor registry unavailable',
    'profile.createProfileHint': 'Create your stall profile before showing QR codes or appearing in the market.',
    'profile.registryHint': 'Set the VendorRegistry contract ID before vendor profiles can load.',
    'profile.applyAsVendor': 'Apply as Vendor',
    'profile.vendorName': 'Vendor Name',
    'profile.vendorNamePlaceholder': 'e.g. Aling Nena',
    'profile.stallNumber': 'Stall Number',
    'profile.stallNumberPlaceholder': 'e.g. Stall 14',
    'profile.phone': 'Phone',
    'profile.phonePlaceholder': '09XX XXX XXXX',
    'profile.productType': 'Product Type',
    'profile.saving': 'Saving…',
    'profile.saveChanges': 'Save changes',
    'profile.updateSuccess': 'Profile updated!',
    'profile.updateFailed': 'Update failed',
    'profile.stall': 'Stall',
    'profile.product': 'Product',
    'profile.title': 'My Profile',
    'profile.sub': 'Manage your account and notifications',
    'profile.wallet': 'Wallet',
    'profile.balance': 'Balance',
    'profile.copy': 'Copy address',
    'profile.copied': 'Copied!',
    'profile.explorer': 'View on Stellar Expert',
    'profile.notifications': 'Notifications',
    'profile.notifDesc': 'Get alerts on utang reminders and receipts',
    'profile.market': 'Browse Market',
    'profile.marketSub': 'Find vendors near you',
    'profile.cashIn': 'Cash In',
    'profile.cashInSub': 'PHP → XLM via PDAX',
    'profile.cashOut': 'Cash Out',
    'profile.cashOutSub': 'XLM → PHP to your bank',
    'profile.walletTest': 'Testnet Wallet Check',
    'profile.walletTestSub': 'Send small XLM and view proof',
    'profile.preferences': 'Display',
    'profile.prefDesc': 'Choose how amounts are shown',
    'profile.privacy': 'Privacy',
    'profile.privacyDesc': 'Hide balance figures from view',
    'profile.notConnected': 'Connect your wallet to see your profile',
    
    // Customer Home
    'home.balance': 'Wallet Balance',
    'home.totalSpent': 'Total Spent',
    'home.transactions': 'Transactions',
    'home.utangBalance': 'Utang Balance',
    'home.utangOverdue': 'Overdue Utang!',
    'home.overdueDesc': (params: TParams) => `${params.count} agreement${Number(params.count) > 1 ? 's' : ''} overdue`,
    'home.activeDesc': (params: TParams) => `${params.count} active agreement${Number(params.count) > 1 ? 's' : ''}`,
    'home.scanBtn': 'Scan to Pay',
    'home.scanSub': 'Aim at any PalengkePay QR',
    'home.vendors': 'Find Vendors',
    'home.vendorsSub': 'Browse market',
    'home.history': 'History',
    'home.historySub': 'Past payments',
    'home.recentPayments': 'Recent Payments',
    'home.viewAll': 'View all',
    'home.emptyTitle': 'No payments yet',
    'home.emptyDesc': 'Scan a vendor QR to get started',
    'home.scanNow': 'Scan Now',
    'home.notConnected': 'Not connected',
    'home.installmentsUnavailable': 'Installments unavailable',
    'home.retryInstallments': 'Retry loading installments',
    'home.loadFailed': 'Failed to load recent payments',
    'home.retry': 'Retry',
    'home.connectWalletDetail': 'Connect your wallet to view your balance, recent payments, and installment plans.',
    'home.receiveTitle': 'Receive Payment',
    'home.receiveSub': 'Show this QR to share your wallet address',
    'home.receiveBtn': 'Receive',
    'home.copyAddress': 'Copy address',
    'home.addressCopied': 'Address copied!',
    'home.closeModal': 'Close',
    
    // Customer History
    'history.header': 'Payment History',
    'history.totalSpentSub': 'XLM total spent',
    'history.transactions': 'Transactions',
    'history.avgPerPayment': 'Avg per payment',
    'history.emptyTitle': 'No payments yet',
    'history.emptyDesc': 'Scan a vendor QR code to get started',
    'history.scanBtn': 'Scan to Pay',
    'history.loadFailed': 'Failed to load history',
    'history.retry': 'Retry',
    'history.connectWalletDetail': 'Connect your wallet to load your payment history and receipts.',
    
    // Customer Cashin
    'cashin.title': 'Cash In',
    'cashin.subtitle': 'PHP → XLM via PDAX',
    'cashin.amountPhp': 'Amount (PHP)',
    'cashin.minAmount': 'Min 50 PHP',
    'cashin.getQuote': 'Get quote',
    'cashin.poweredBy': 'Powered by PDAX (mock mode in dev)',
    'cashin.youPay': 'You pay',
    'cashin.youReceive': 'You receive',
    'cashin.rate': 'Rate',
    'cashin.feeSpread': 'Fee / spread',
    'cashin.partnerApiMode': 'Partner API mode',
    'cashin.manualOperatorMode': 'Manual operator mode',
    'cashin.demoSettlementMode': 'Demo settlement mode',
    'cashin.rateSimulator': 'Rate and fee simulator',
    'cashin.grossPhp': 'Gross PHP',
    'cashin.fee': 'Fee',
    'cashin.spread': 'Spread',
    'cashin.estXlm': 'Est. XLM',
    'cashin.quoteHint': (params: TParams) => `Final quote locks the PDAX-style rate for ${params.seconds} after confirmation.`,
    'cashin.qrInstruction': 'QR Ph-style payment instruction',
    'cashin.payVia': (params: TParams) => `Pay via ${params.rail}`,
    'cashin.sendInstruction': (params: TParams) => `Send PHP ${params.amount} from GCash, QR Ph, or bank transfer. Use this reference:`,
    'cashin.copied': 'Copied',
    'cashin.copy': 'Copy',
    'cashin.qrCopied': 'QR payload copied',
    'cashin.copyQrPayload': 'Copy QR payload',
    'cashin.expiresIn': (params: TParams) => `Quote expires in ${params.seconds}s · ${params.time}`,
    'cashin.demoModeNotice': 'Demo settlement mode',
    'cashin.paymentProof': 'Payment proof',
    'cashin.senderNamePlaceholder': 'Sender name',
    'cashin.referencePlaceholder': 'GCash / QR Ph reference number',
    'cashin.confirmationCheckbox': 'I sent the PHP payment and understand operator confirmation is required in demo settlement mode.',
    'cashin.proceedButton': 'I have paid — proceed',
    'cashin.cancel': 'Cancel',
    'cashin.submittingClaim': 'Submitting payment claim…',
    'cashin.waitingOperator': 'Waiting for operator to confirm your PHP payment',
    'cashin.sendingXlm': 'Sending XLM to your wallet…',
    'cashin.operatorWaitMessage': 'We will push-notify you once operator releases XLM. You can close this page.',
    'cashin.keepPageOpen': 'Please keep this page open',
    'cashin.completeTitle': 'Cashin complete',
    'cashin.inYourWallet': 'XLM in your wallet',
    'cashin.done': 'Done',
    'cashin.failedTitle': 'Cashin failed',
    'cashin.unknownError': 'Unknown error',
    'cashin.tryAgain': 'Try again',
    'cashin.notificationTitle': 'PalengkePay — payment received',
    'cashin.notificationBodyComplete': 'XLM in your wallet',
    'cashin.notificationBodyWaiting': 'Waiting on operator to release XLM',
    
    // Customer Cashout
    'cashout.title': 'Cash Out',
    'cashout.subtitle': 'XLM → PHP via PDAX',
    'cashout.amountXlm': 'Amount (XLM)',
    'cashout.balance': (params: TParams) => `Balance: ${params.balance} XLM`,
    'cashout.payoutMethod': 'Payout method',
    'cashout.accountNumber': 'Account / Number',
    'cashout.ewalletPlaceholder': '09171234567',
    'cashout.bankPlaceholder': 'Bank account number',
    'cashout.beneficiaryName': 'Beneficiary name',
    'cashout.continue': 'Continue',
    'cashout.footerNote': 'Min 5 XLM · Powered by PDAX (mock mode in dev)',
    'cashout.sendXlmToAnchor': 'Send XLM to anchor',
    'cashout.memoRequired': 'Memo (required)',
    'cashout.copied': 'Copied',
    'cashout.copyMemo': 'Copy memo',
    'cashout.amountLabel': 'Amount:',
    'cashout.settlementNote': (params: TParams) => `Settlement: PDAX-style liquidity quote to GCash / QR Ph settlement rail. Spread: ${params.spread} bps.`,
    'cashout.sendXlmButton': 'Send XLM from my wallet',
    'cashout.cancel': 'Cancel',
    'cashout.sendingXlm': 'Sending XLM…',
    'cashout.verifyingAndCalculating': 'Verifying on Stellar & calculating PHP payout…',
    'cashout.awaitingOperator': (params: TParams) => `Awaiting operator to release PHP via ${params.rail}`,
    'cashout.operatorWaitMessage': 'We will push-notify you once operator marks PHP sent. You can close this page.',
    'cashout.keepPageOpen': 'Please keep this page open',
    'cashout.completeTitle': 'Cashout complete',
    'cashout.sentToRail': (params: TParams) => `PHP ${params.amount} sent to ${params.rail}`,
    'cashout.reference': 'Ref',
    'cashout.done': 'Done',
    'cashout.failedTitle': 'Cashout failed',
    'cashout.unknownError': 'Unknown error',
    'cashout.tryAgain': 'Try again',
    'cashout.notificationComplete': 'PalengkePay — cashout complete',
    'cashout.notificationPaying': 'PalengkePay — paying out',
    'cashout.notificationBodyComplete': (params: TParams) => `PHP ${params.amount} sent to ${params.rail}`,
    'cashout.notificationBodyPaying': 'PHP rail in flight, you will be notified',
  },
  tl: {
    // Common
    'common.today': 'Ngayon',
    'common.yesterday': 'Kahapon',
    'common.wallet': 'Pitaka',
    'common.back': 'Bumalik',
    
    // Vendor Home
    'vendor.greeting': (params: TParams) => `${params.time}, ${params.name}`,
    'vendor.goodMorning': 'Magandang umaga',
    'vendor.goodAfternoon': 'Magandang tanghali',
    'vendor.goodEvening': 'Magandang gabi',
    'vendor.todayEarnings': 'Kita Ngayon',
    'vendor.paymentsToday': (params: TParams) => `${params.count} bayad ngayon`,
    'vendor.allTimeEarnings': 'Kabuuan',
    'vendor.totalPayments': 'Mga Bayad',
    'vendor.showQR': 'Ipakita ang QR',
    'vendor.showQRSub': 'I-display para tumanggap ng bayad',
    'vendor.utang': 'Utang',
    'vendor.utangSub': 'Installment na kredito',
    'vendor.recentPayments': 'Mga Huling Bayad',
    'vendor.viewAll': 'Lahat',
    'vendor.loadFailed': 'Hindi na-load',
    'vendor.retry': 'Subukan ulit',
    'vendor.emptyTitle': 'Wala pang bayad',
    'vendor.emptyDesc': 'I-share ang iyong QR para makatanggap',
    'vendor.showQRBtn': 'Ipakita ang QR ko',
    'vendor.stallOpen': 'Bukas ang stall',
    'vendor.stallClosed': 'Sarado ang stall',
    'vendor.tapToClose': 'I-tap para magsara',
    'vendor.tapToOpen': 'I-tap para magbukas',
    'vendor.statusToastOpen': 'Bukas na ang stall. Makikita ka ng mga kustomer.',
    'vendor.statusToastClosed': 'Sarado na. Hindi ka mapapakita sa live directory.',
    'vendor.statusError': 'Hindi na-update ang status',
    
    // Vendor Apply
    'apply.title': 'Mag-apply bilang Vendor',
    'apply.subtitle': 'I-submit ang stall info. Aaprubahan ng admin ang iyong registration.',
    'apply.connectWallet': 'I-connect ang Wallet',
    'apply.registryNotConfigured': 'Hindi na-configure ang vendor registry',
    'apply.registryHint': 'I-set ang VITE_VENDOR_REGISTRY_CONTRACT_ID bago mag-submit ng application.',
    'apply.registryNotConfiguredShort': 'Hindi na-configure ang registry',
    'apply.selectStallError': 'Pumili muna ng stall number.',
    'apply.successToast': 'Na-submit ang application! Naghihintay ng admin approval.',
    'apply.successTitle': 'Na-submit ang Application!',
    'apply.successDesc': 'Susuriin at aaprubahan ng admin ang iyong registration.',
    'apply.yourDetails': 'Iyong Detalye',
    'apply.stallName': 'Pangalan ng Stall',
    'apply.stall': 'Stall',
    'apply.product': 'Produkto',
    'apply.phone': 'Telepono',
    'apply.viewOnExpert': 'Tingnan sa Stellar Expert',
    'apply.stallNameLabel': 'Pangalan ng Stall',
    'apply.stallNamePlaceholder': 'Hal. Aling Nena Sari-Sari',
    'apply.productTypeLabel': 'Uri ng Produkto',
    'apply.selectStallLabel': 'Piliin ang Stall',
    'apply.phoneLabel': 'Telepono',
    'apply.optional': 'opsyonal',
    'apply.paymentWallet': 'Wallet ng pagbabayad',
    'apply.submitting': 'Isinusumite…',
    'apply.submitButton': 'I-submit ang Application',
    'apply.available': 'Available',
    'apply.occupied': 'Occupied',
    'apply.selected': 'Napili',
    'apply.section': 'Seksyon',
    'apply.stallSelected': (params: TParams) => `Napili ang Stall ${params.stall}`,
    
    // Vendor Transactions
    'transactions.header': 'Lahat ng Kita',
    'transactions.allTimeSub': 'XLM kabuuan',
    'transactions.todayEarnings': 'Kita Ngayon',
    'transactions.paymentsToday': 'Mga Bayad Ngayon',
    'transactions.incomeProofPack': 'Income Proof Pack',
    'transactions.incomeProofDesc': 'Exportable vendor proof na may source labels at Testnet caveats.',
    'transactions.transactions': 'Mga Transaksyon',
    'transactions.totalXlm': 'Kabuuang XLM',
    'transactions.phpEst': 'PHP tantiya',
    'transactions.dateRange': 'Saklaw ng petsa',
    'transactions.unavailable': 'Hindi available',
    'transactions.paymentData': 'Data ng bayad',
    'transactions.repaymentData': 'Data ng repayment',
    'transactions.liveProof': 'Live proof',
    'transactions.customers': 'Mga customer',
    'transactions.present': 'Presente',
    'transactions.missing': 'Nawawala',
    'transactions.attached': 'Naka-attach',
    'transactions.notAttached': 'Hindi naka-attach',
    'transactions.needed': 'Kailangan',
    'transactions.paymentRows': 'Mga payment row',
    'transactions.liveHash': 'Live hash',
    'transactions.repayments': 'Mga repayment',
    'transactions.caveats': 'Mga caveat',
    'transactions.certificate': 'Sertipiko',
    'transactions.print': 'I-print',
    'transactions.copyLiveHash': 'Kopyahin ang live hash',
    'transactions.captureHashHint': 'Kumuha ng isang tunay na Testnet payment bago ibahagi ang sertipiko na ito sa labas ng demo team.',
    'transactions.recoveryDesk': 'Transaction Recovery Desk',
    'transactions.recoveryDesc': 'Receipt lookup, resend path, at sponsor diagnostics para sa mga isyu sa pagbabayad ng customer.',
    'transactions.receiptLookup': 'Receipt lookup',
    'transactions.noReceiptYet': 'Wala pang receipt',
    'transactions.checkReceipt': 'Tingnan ang receipt',
    'transactions.resendPath': 'Resend path',
    'transactions.sponsorDiagnostics': 'Sponsor diagnostics',
    'transactions.lookupByHash': 'Maghanap gamit ang hash/reference',
    'transactions.lookupHelp': 'I-paste ang transaction hash, contract payment ID, o local receipt reference mula sa customer message.',
    'transactions.lookupPlaceholder': 'Hash, #42, o proof ref',
    'transactions.useLatest': 'Gamitin ang pinakabago',
    'transactions.clear': 'I-clear',
    'transactions.openMatchedReceipt': 'Buksan ang matched receipt',
    'transactions.copyReference': 'Kopyahin ang reference',
    'transactions.receiptReference': 'Receipt reference',
    'transactions.searchReceipts': 'Maghanap ng receipts',
    'transactions.searchPlaceholder': 'Hash, memo, source, amount',
    'transactions.searchResultInfo': (params: TParams) => `Ipinapakita ang ${params.shown} ng ${params.total} receipt rows. Gumagamit ang exports ng napiling period at kasalukuyang search filter.`,
    'transactions.failedTitle': 'Hindi na-load',
    'transactions.retry': 'Subukan ulit',
    'transactions.emptyTitle': 'Wala pang transaksyon',
    'transactions.emptyDesc': 'I-share ang QR code para matanggap ang iyong unang bayad',
    'transactions.showQr': 'Ipakita ang QR',
    'transactions.noMatching': 'Walang matching receipts',
    'transactions.noMatchingHint': 'Subukan ang hash, customer wallet, memo, source label, o amount.',
    'transactions.clearSearch': 'I-clear ang search',

    // Scan
    'scan.title': 'I-Scan para Magbayad',
    'scan.manualTitle': 'Ilagay ang Address',
    'scan.payTitle': 'Magbayad sa Vendor',
    'scan.confirmTitle': 'Kumpirmahin ang Bayad',
    'scan.doneTitle': 'Naipadala ang Bayad!',
    'scan.utangOfferTitle': 'Alok ng Installment',
    'scan.utangDoneTitle': 'Tinanggap!',
    'scan.walletRequiredDetail': 'I-connect ang iyong wallet bago mag-scan ng payment QRs o tumanggap ng installment offers.',
    'scan.scanHeader': 'I-Scan ang QR',
    'scan.scanSub': 'Payment QR at utang offer — auto-detect',
    'scan.vendorAddressLabel': 'Wallet Address ng Vendor',
    'scan.vendorAddressHint': '56-character Stellar address na nagsisimula sa G',
    'scan.continue': 'Magpatuloy',
    'scan.payingTo': 'Nagbabayad kay',
    'scan.amountToPay': 'Halagang Babayaran',
    'scan.priceLock': 'Price lock',
    'scan.expires': 'Mag-e-expire',
    'scan.onChainReceipt': 'On-chain receipt — naitala ng PalengkePayment',
    'scan.gasless': 'Gasless — libre ang fees, walang gastos sa iyo',
    'scan.confirmAndSign': 'Kumpirmahin at I-sign',
    'scan.paymentComplete': 'Bayad na!',
    'scan.toVendor': (params: TParams) => `kay ${params.name}`,
    'scan.dualReceipt': 'Dual-currency receipt',
    'scan.customerPaid': 'Binayad ng customer',
    'scan.settledOnStellar': 'Na-settle sa Stellar',
    'scan.digitalReceipt': 'Digital Resibo',
    'scan.stellarExpert': 'Stellar Expert',
    'scan.payAgain': 'Bayad Ulit',
    'scan.home': 'Home',
    'scan.installmentOffer': 'Installment Credit Offer',
    'scan.reviewBeforeAccept': 'Suriin bago tanggapin',
    'scan.itemsBought': 'Mga Biniling Item',
    'scan.interval': 'agwat',
    'scan.vendor': 'Vendor',
    'scan.contractNotConfigured': 'Hindi na-configure ang contract',
    'scan.contractHint': 'Maaaring tingnan ang alok na ito, ngunit hindi ito matatanggap hanggang hindi nase-set ang VITE_UTANG_ESCROW_CONTRACT_ID.',
    'scan.acceptAndSign': 'Tanggapin at I-sign',
    'scan.confirmInWallet': 'Kumpirmahin sa iyong wallet…',
    'scan.confirmWalletHint': 'Sa mobile: buksan ang LOBSTR app at i-approve.',
    'scan.tryAgain': 'Subukan Ulit',
    'scan.agreementAccepted': 'Kasunduan Tinanggap!',
    'scan.agreementActive': 'Aktibo na ang installment plan.',
    'scan.viewUtang': 'Tingnan ang Utang',
    'scan.utangWrongWallet': 'Ang installment offer na ito ay itinalaga sa ibang customer wallet',
    'scan.utangFailed': 'Nabigo ang transaksyon — suriin ang wallet at subukan muli',
    'scan.interval.weekly': 'lingguhan',
    'scan.interval.biweekly': 'bawat dalawang linggo',
    'scan.interval.monthly': 'buwanan',
    'scan.interval.every': (params: TParams) => `bawat ${params.days} araw`,
    'scan.manualEntry': 'Manual na pagpasok',
    'scan.uploadQR': 'Mag-upload ng QR image',
    'scan.bottomHint': 'I-align ang QR code sa loob ng brackets',
    
    // Vendor Utang
    'vendorUtang.title': 'Utang (BNPL)',
    'vendorUtang.subtitle': 'I-manage ang mga installment',
    'vendorUtang.newUtang': 'Bagong Utang',
    'vendorUtang.itemsRequired': 'Ilagay ang mga items',
    'vendorUtang.validAmountRequired': 'Ilagay ang tamang halaga',
    'vendorUtang.validWalletRequired': 'Ilagay ang wastong Stellar wallet address (G..., 56 chars)',
    'vendorUtang.transactionCancelled': 'Kinansela ang transaksyon',
    'vendorUtang.showQRToCustomer': 'Ipakita sa Customer',
    'vendorUtang.serviceFee': 'Bayad sa Serbisyo',
    'vendorUtang.newAgreement': 'Bagong Kasunduan',
    'vendorUtang.totalOutstanding': 'Kabuuang Natatanggap',
    'vendorUtang.activeAgreements': (params: TParams) => `${params.count} aktibong kasunduan`,
    'vendorUtang.collectionsReport': 'Collections Report',
    'vendorUtang.collectionsDesc': 'Buod ng aktibo, tapos, overdue, at defaulted na kasunduan.',
    'vendorUtang.active': 'Aktibo',
    'vendorUtang.completed': 'Tapos na',
    'vendorUtang.overdue': 'Overdue',
    'vendorUtang.defaulted': 'Defaulted',
    'vendorUtang.outstanding': 'Natitira',
    'vendorUtang.collected': 'Nakolekta',
    'vendorUtang.loadFailed': 'Hindi ma-load ang mga kasunduan',
    'vendorUtang.retry': 'Subukan ulit',
    'vendorUtang.noAgreements': 'Walang kasunduan pa',
    'vendorUtang.noFilteredAgreements': (params: TParams) => `Walang ${params.filter} na kasunduan`,
    'vendorUtang.emptyDesc': 'Gumawa ng installment para sa customer via QR o manual',
    'vendorUtang.escrowWarning': 'I-set ang VITE_UTANG_ESCROW_CONTRACT_ID para ma-enable ang BNPL.',
    'vendorUtang.customerWalletAddress': 'Customer Wallet Address',
    'vendorUtang.scanCustomerWallet': 'I-scan ang wallet ng customer',
    'vendorUtang.items': 'Mga Items',
    'vendorUtang.itemsHint': '(binibili nila sa credit)',
    'vendorUtang.itemsPlaceholder': 'hal. 5kg bigas, 2kg baboy, gulay',
    'vendorUtang.totalAmount': 'Kabuuang Halaga (XLM)',
    'vendorUtang.installments': 'Installments',
    'vendorUtang.interval': 'Agwat',
    'vendorUtang.generateQRCode': 'I-generate ang QR Code',
    'vendorUtang.createCustomerQR': 'Gumawa ng Customer QR',
    'vendorUtang.agreementSummary': 'Buod ng Kasunduan',
    'vendorUtang.serviceFeeTitle': 'Bayad sa Serbisyo ng PalengkePay',
    'vendorUtang.serviceFeeDesc': 'Bayad sa paglikha ng QR utang',
    'vendorUtang.serviceFeeNote': 'One-time fee bawat QR na kasunduan. Bayad sa PalengkePay para ma-register on-chain.',
    'vendorUtang.payAndGenerateQR': (params: TParams) => `Bayaran ang ${params.fee} XLM at I-generate ang QR`,
    'vendorUtang.confirmInWallet': 'Kumpirmahin sa wallet…',
    'vendorUtang.downloadQR': 'I-download ang QR Image',
    'vendorUtang.howItWorks': 'Paano ito gumagana',
    'vendorUtang.step1': 'Ipakita itong QR sa iyong customer',
    'vendorUtang.step2': 'Buksan ng customer ang PalengkePay → My Utang → i-tap ang Scan',
    'vendorUtang.step3': 'Tingnan ng customer ang detalye at i-tap ang Tanggapin',
    'vendorUtang.step4': 'Awtomatikong nai-register ang kasunduan on-chain',
    'vendorUtang.done': 'Tapos',
    
    // Customer Utang
    'customerUtang.title': 'Aking Utang',
    'customerUtang.subtitle': 'Iyong mga installment plans',
    'customerUtang.uploadQR': 'Mag-upload ng QR',
    'customerUtang.reading': 'Binabasa…',
    'customerUtang.uploadErrorInvalid': 'Ang QR na ito ay hindi installment offer. Gamitin ang Scan to Pay para sa payment QRs.',
    'customerUtang.uploadErrorRead': 'Hindi mabasa ang QR mula sa larawan. Subukan ang mas malinaw na larawan.',
    'customerUtang.connectWalletDetail': 'I-connect ang iyong wallet para tingnan ang installment plans at tumanggap ng vendor credit offers.',
    'customerUtang.contractNotConfigured': 'Hindi na-configure ang installment contract',
    'customerUtang.contractHint': 'I-set ang VITE_UTANG_ESCROW_CONTRACT_ID bago makapag-load o tumanggap ng installment plans ang mga customer.',
    'customerUtang.loadFailed': 'Hindi ma-load ang installment plans',
    'customerUtang.retry': 'Subukan ulit',
    'customerUtang.totalDue': 'Kabuuang Dapat Bayaran — Susunod na Installments',
    'customerUtang.activePlans': (params: TParams) => `${params.count} aktibong plan${params.count !== 1 ? '' : ''}`,
    'customerUtang.filter.active': 'Aktibo',
    'customerUtang.filter.defaulted': 'Default',
    'customerUtang.filter.completed': 'Tapos na',
    'customerUtang.filter.all': 'Lahat',
    'customerUtang.emptyActive': 'Walang aktibong plan',
    'customerUtang.emptyFiltered': (params: TParams) => `Walang ${params.filter} na plans`,
    'customerUtang.emptyDesc': 'Humingi ng installment QR sa iyong vendor, tapos i-scan o i-upload.',
    'customerUtang.scanQR': 'I-scan ang QR',
    'customerUtang.installmentOffer': 'Installment Credit Offer',
    'customerUtang.reviewBeforeAccept': 'Suriin bago tanggapin',
    'customerUtang.items': 'Mga Item',
    'customerUtang.total': 'kabuuang',
    'customerUtang.interval': 'agwat',
    'customerUtang.vendor': 'Vendor',
    'customerUtang.acceptAndSign': 'Tanggapin at I-sign',
    'customerUtang.confirmInWallet': 'Kumpirmahin sa iyong wallet…',
    'customerUtang.confirmWalletHint': 'Sa mobile: buksan ang LOBSTR app at i-approve.',
    'customerUtang.agreementAccepted': 'Tinanggap ang kasunduan!',
    'customerUtang.viewOnExpert': 'Tingnan sa Stellar Expert',
    'customerUtang.close': 'Isara',
    'customerUtang.tryAgain': 'Subukan ulit',
    'customerUtang.offerWrongWallet': 'Ang installment offer na ito ay itinalaga sa ibang customer wallet',
    'customerUtang.offerFailed': 'Nabigo ang transaksyon — suriin ang wallet at subukan muli',
    'customerUtang.payInstallment': 'Bayaran ang Installment',
    'customerUtang.installmentNumber': (params: TParams) => `Installment ${params.current} ng ${params.total}`,
    'customerUtang.confirmPayment': 'Kumpirmahin ang Bayad',
    'customerUtang.preparing': 'Inihahanda…',
    'customerUtang.processing': 'Pinoproseso…',
    'customerUtang.paymentComplete': 'Bayad na!',
    'customerUtang.interval.weekly': 'lingguhan',
    'customerUtang.interval.biweekly': 'bawat dalawang linggo',
    'customerUtang.interval.monthly': 'buwanan',
    'customerUtang.interval.every': (params: TParams) => `bawat ${params.days} araw`,
    
    // Vendor QR
    'qr.connectWalletDetail': 'I-connect ang iyong vendor wallet para ipakita ang QR code na gagamitin ng customer sa pagbabayad.',
    'qr.yourQRCode': 'Iyong QR Code',
    'qr.myQRCode': 'Aking QR Code',
    'qr.registerFirst': 'Magrehistro muna',
    'qr.stall': 'Stall',
    'qr.registerStallFirst': 'Irehistro muna ang iyong stall',
    'qr.registryUnavailable': 'Hindi available ang vendor registry',
    'qr.registerHint': 'Lalabas ang iyong customer QR pagkatapos mairehistro ang iyong vendor profile.',
    'qr.registryHint': 'I-set ang vendor registry contract ID bago mag-load ang QR profiles.',
    'qr.applyAsVendor': 'Mag-apply bilang Vendor',
    'qr.bottomHint': 'I-scan ng customer para magbayad · works offline',
    'qr.printReady': 'Print-ready QR kit',
    'qr.posterPreview': 'Poster at sticker preview',
    'qr.printKit': 'I-print ang QR kit',
    'qr.scanToPay': 'I-scan para magbayad',
    'qr.step1': 'Buksan ang PalengkePay',
    'qr.step2': 'I-scan itong QR',
    'qr.step3': 'Kumpirmahin sa wallet',
    'qr.sticker': 'Sticker',
    'qr.vendorQR': 'Vendor QR',
    'qr.stickerHint': 'I-scan ng customer para magbayad gamit ang wallet.',
    
    // Vendor Profile
    'profile.connectWalletDetail': 'I-connect ang iyong vendor wallet para tingnan o i-update ang iyong stall profile.',
    'profile.addressCopied': 'Na-copy ang address sa clipboard!',
    'profile.disconnected': 'Na-disconnect ang wallet',
    'profile.vendor': 'Vendor',
    'profile.copyAddress': 'Kopyahin ang address',
    'profile.active': 'Aktibo',
    'profile.inactive': 'Hindi Aktibo',
    'profile.disconnect': 'Idiskonekta',
    'profile.disconnectTitle': 'Idiskonekta ang Wallet?',
    'profile.disconnectMessage': 'Sigurado ka bang gusto mong idiskonekta ang iyong wallet? Kakailanganin mong mag-connect muli para ma-access ang iyong vendor profile.',
    'profile.cancel': 'Kanselahin',
    'profile.disconnectConfirm': 'Idiskonekta',
    'profile.disconnecting': 'Dini-disconnect...',
    'profile.withdrawEarnings': 'Mag-withdraw ng kita',
    'profile.withdrawDesc': 'I-cash out ang XLM → PHP sa pamamagitan ng PDAX',
    'profile.ratings': 'rating',
    'profile.noRatingsShort': 'Wala pang rating',
    'profile.transactions': 'Mga Transaksyon',
    'profile.volume': 'Volume',
    'profile.stallDetails': 'Detalye ng Stall',
    'profile.edit': 'I-edit',
    'profile.noProfile': 'Wala pang vendor profile',
    'profile.registryUnavailable': 'Hindi available ang vendor registry',
    'profile.createProfileHint': 'Gumawa ng iyong stall profile bago magpakita ng QR codes o lumabas sa market.',
    'profile.registryHint': 'I-set ang VendorRegistry contract ID bago mag-load ang vendor profiles.',
    'profile.applyAsVendor': 'Mag-apply bilang Vendor',
    'profile.vendorName': 'Pangalan ng Vendor',
    'profile.vendorNamePlaceholder': 'Hal. Aling Nena',
    'profile.stallNumber': 'Stall Number',
    'profile.stallNumberPlaceholder': 'Hal. Stall 14',
    'profile.phone': 'Telepono',
    'profile.phonePlaceholder': '09XX XXX XXXX',
    'profile.productType': 'Uri ng Produkto',
    'profile.saving': 'Sine-save…',
    'profile.saveChanges': 'I-save ang mga pagbabago',
    'profile.updateSuccess': 'Na-update ang profile!',
    'profile.updateFailed': 'Nabigo ang pag-update',
    'profile.stall': 'Stall',
    'profile.product': 'Produkto',
    'profile.title': 'Aking Profile',
    'profile.sub': 'I-manage ang account at notifications',
    'profile.wallet': 'Pitaka',
    'profile.balance': 'Balanse',
    'profile.copy': 'Kopyahin ang address',
    'profile.copied': 'Nakopya!',
    'profile.explorer': 'Tingnan sa Stellar Expert',
    'profile.notifications': 'Mga Notification',
    'profile.notifDesc': 'Tumanggap ng alerts sa utang at resibo',
    'profile.market': 'Tingnan ang Market',
    'profile.marketSub': 'Hanapin ang mga vendor',
    'profile.cashIn': 'Mag Cash In',
    'profile.cashInSub': 'PHP → XLM sa PDAX',
    'profile.cashOut': 'Mag Cash Out',
    'profile.cashOutSub': 'XLM → PHP papunta sa bangko',
    'profile.walletTest': 'Testnet Wallet Check',
    'profile.walletTestSub': 'Magpadala ng maliit na XLM',
    'profile.preferences': 'Display',
    'profile.prefDesc': 'Piliin kung paano ipakita ang halaga',
    'profile.privacy': 'Privacy',
    'profile.privacyDesc': 'Itago ang balanse',
    'profile.notConnected': 'I-connect ang wallet para makita ang profile',
    
    // Customer Home
    'home.balance': 'Iyong Balanse',
    'home.totalSpent': 'Kabuuang Gastos',
    'home.transactions': 'Mga Transaksyon',
    'home.utangBalance': 'Utang Balance',
    'home.utangOverdue': 'May Overdue na Utang!',
    'home.overdueDesc': (params: TParams) => `${params.count} kasunduan ang overdue`,
    'home.activeDesc': (params: TParams) => `${params.count} aktibong kasunduan`,
    'home.scanBtn': 'I-Scan at Bayaran',
    'home.scanSub': 'I-aim sa QR ng kahit anong vendor',
    'home.vendors': 'Mga Vendor',
    'home.vendorsSub': 'I-browse ang palengke',
    'home.history': 'Kasaysayan',
    'home.historySub': 'Mga nakaraang bayad',
    'home.recentPayments': 'Mga Huling Bayad',
    'home.viewAll': 'Lahat',
    'home.emptyTitle': 'Wala pang bayad',
    'home.emptyDesc': 'I-scan ang QR ng vendor para magsimula',
    'home.scanNow': 'I-scan Ngayon',
    'home.notConnected': 'Hindi nakakonekta',
    'home.installmentsUnavailable': 'Hindi available ang mga installment',
    'home.retryInstallments': 'Subukang i-load muli ang mga installment',
    'home.loadFailed': 'Hindi ma-load ang mga recent payment',
    'home.retry': 'Subukan ulit',
    'home.connectWalletDetail': 'I-connect ang iyong wallet para tingnan ang iyong balanse, mga recent payment, at installment plans.',
    'home.receiveTitle': 'Tumanggap ng Bayad',
    'home.receiveSub': 'Ipakita ang QR para ibahagi ang iyong wallet address',
    'home.receiveBtn': 'Tanggap',
    'home.copyAddress': 'Kopyahin ang address',
    'home.addressCopied': 'Nakopya na ang address!',
    'home.closeModal': 'Isara',
    
    // Customer History
    'history.header': 'Kasaysayan ng Bayad',
    'history.totalSpentSub': 'XLM kabuuang gastos',
    'history.transactions': 'Mga Transaksyon',
    'history.avgPerPayment': 'Avg bawat bayad',
    'history.emptyTitle': 'Walang bayad pa',
    'history.emptyDesc': 'I-scan ang QR ng vendor para magsimula',
    'history.scanBtn': 'I-scan Ngayon',
    'history.loadFailed': 'Hindi ma-load ang history',
    'history.retry': 'Subukan ulit',
    'history.connectWalletDetail': 'I-connect ang iyong wallet para i-load ang iyong payment history at receipts.',
    
    // Customer Cashin
    'cashin.title': 'Mag-cash in',
    'cashin.subtitle': 'PHP → XLM sa pamamagitan ng PDAX',
    'cashin.amountPhp': 'Halaga (PHP)',
    'cashin.minAmount': 'Min 50 PHP',
    'cashin.getQuote': 'Kumuha ng quote',
    'cashin.poweredBy': 'Pinagagana ng PDAX (mock mode sa dev)',
    'cashin.youPay': 'Babayaran mo',
    'cashin.youReceive': 'Matatanggap mo',
    'cashin.rate': 'Rate',
    'cashin.feeSpread': 'Bayad / spread',
    'cashin.partnerApiMode': 'Partner API mode',
    'cashin.manualOperatorMode': 'Manual operator mode',
    'cashin.demoSettlementMode': 'Demo settlement mode',
    'cashin.rateSimulator': 'Rate at fee simulator',
    'cashin.grossPhp': 'Gross PHP',
    'cashin.fee': 'Bayad',
    'cashin.spread': 'Spread',
    'cashin.estXlm': 'Tantiya XLM',
    'cashin.quoteHint': (params: TParams) => `Ang final quote ay nagla-lock ng PDAX-style rate sa loob ng ${params.seconds} pagkatapos ng kumpirmasyon.`,
    'cashin.qrInstruction': 'QR Ph-style payment instruction',
    'cashin.payVia': (params: TParams) => `Magbayad sa pamamagitan ng ${params.rail}`,
    'cashin.sendInstruction': (params: TParams) => `Magpadala ng PHP ${params.amount} mula sa GCash, QR Ph, o bank transfer. Gamitin ang reference na ito:`,
    'cashin.copied': 'Na-copy',
    'cashin.copy': 'Kopyahin',
    'cashin.qrCopied': 'Na-copy ang QR payload',
    'cashin.copyQrPayload': 'Kopyahin ang QR payload',
    'cashin.expiresIn': (params: TParams) => `Mag-e-expire ang quote sa ${params.seconds}s · ${params.time}`,
    'cashin.demoModeNotice': 'Demo settlement mode',
    'cashin.paymentProof': 'Patunay ng pagbabayad',
    'cashin.senderNamePlaceholder': 'Pangalan ng nagpadala',
    'cashin.referencePlaceholder': 'GCash / QR Ph reference number',
    'cashin.confirmationCheckbox': 'Ipinadala ko ang PHP payment at nauunawaan ko na kinakailangan ang kumpirmasyon ng operator sa demo settlement mode.',
    'cashin.proceedButton': 'Nagbayad na ako — magpatuloy',
    'cashin.cancel': 'Kanselahin',
    'cashin.submittingClaim': 'Isinusumite ang claim ng pagbabayad…',
    'cashin.waitingOperator': 'Naghihintay ng kumpirmasyon ng operator sa iyong PHP payment',
    'cashin.sendingXlm': 'Ipinapadala ang XLM sa iyong wallet…',
    'cashin.operatorWaitMessage': 'Magpapadala kami ng push notification kapag nailabas na ng operator ang XLM. Maaari mong isara ang pahinang ito.',
    'cashin.keepPageOpen': 'Mangyaring panatilihing bukas ang pahinang ito',
    'cashin.completeTitle': 'Kumpleto ang Cash in',
    'cashin.inYourWallet': 'XLM sa iyong wallet',
    'cashin.done': 'Tapos',
    'cashin.failedTitle': 'Nabigo ang Cash in',
    'cashin.unknownError': 'Hindi kilalang error',
    'cashin.tryAgain': 'Subukan muli',
    'cashin.notificationTitle': 'PalengkePay — natanggap ang pagbabayad',
    'cashin.notificationBodyComplete': 'XLM sa iyong wallet',
    'cashin.notificationBodyWaiting': 'Naghihintay sa operator na ilabas ang XLM',
    
    // Customer Cashout
    'cashout.title': 'Mag-cash out',
    'cashout.subtitle': 'XLM → PHP sa pamamagitan ng PDAX',
    'cashout.amountXlm': 'Halaga (XLM)',
    'cashout.balance': (params: TParams) => `Balansya: ${params.balance} XLM`,
    'cashout.payoutMethod': 'Paraan ng payout',
    'cashout.accountNumber': 'Account / Numero',
    'cashout.ewalletPlaceholder': '09171234567',
    'cashout.bankPlaceholder': 'Numero ng bank account',
    'cashout.beneficiaryName': 'Pangalan ng beneficiary',
    'cashout.continue': 'Magpatuloy',
    'cashout.footerNote': 'Min 5 XLM · Pinagagana ng PDAX (mock mode sa dev)',
    'cashout.sendXlmToAnchor': 'Magpadala ng XLM sa anchor',
    'cashout.memoRequired': 'Memo (kinakailangan)',
    'cashout.copied': 'Na-copy',
    'cashout.copyMemo': 'Kopyahin ang memo',
    'cashout.amountLabel': 'Halaga:',
    'cashout.settlementNote': (params: TParams) => `Settlement: PDAX-style liquidity quote sa GCash / QR Ph settlement rail. Spread: ${params.spread} bps.`,
    'cashout.sendXlmButton': 'Magpadala ng XLM mula sa aking wallet',
    'cashout.cancel': 'Kanselahin',
    'cashout.sendingXlm': 'Ipinapadala ang XLM…',
    'cashout.verifyingAndCalculating': 'Sine-verify sa Stellar at kinukwenta ang PHP payout…',
    'cashout.awaitingOperator': (params: TParams) => `Naghihintay sa operator na ilabas ang PHP sa pamamagitan ng ${params.rail}`,
    'cashout.operatorWaitMessage': 'Magpapadala kami ng push notification kapag nailabas na ng operator ang PHP. Maaari mong isara ang pahinang ito.',
    'cashout.keepPageOpen': 'Mangyaring panatilihing bukas ang pahinang ito',
    'cashout.completeTitle': 'Kumpleto ang Cashout',
    'cashout.sentToRail': (params: TParams) => `PHP ${params.amount} ipinadala sa ${params.rail}`,
    'cashout.reference': 'Ref',
    'cashout.done': 'Tapos',
    'cashout.failedTitle': 'Nabigo ang Cashout',
    'cashout.unknownError': 'Hindi kilalang error',
    'cashout.tryAgain': 'Subukan muli',
    'cashout.notificationComplete': 'PalengkePay — kumpleto ang cashout',
    'cashout.notificationPaying': 'PalengkePay — nagbabayad',
    'cashout.notificationBodyComplete': (params: TParams) => `PHP ${params.amount} ipinadala sa ${params.rail}`,
    'cashout.notificationBodyPaying': 'PHP rail in flight, makakatanggap ka ng notification',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Load saved language from localStorage
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved && (saved === 'en' || saved === 'tl') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', lang);
  }, [lang]);

  const t = (key: string, params?: TParams): string => {
    const translation = translations[lang][key as keyof typeof translations[typeof lang]];
    if (typeof translation === 'function') {
      return translation(params || {});
    }
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}